apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: outbox.event.order
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  topicName: outbox.event.Order
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
